/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade05.view;

/**
 *
 * @author Taila
 */
public class Repetição extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Repetição.class.getName());

    /**
     * Creates new form Repetição
     */
    public Repetição() {
        initComponents();
        
        
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInicio = new javax.swing.JLabel();
        jFim = new javax.swing.JLabel();
        jPasso = new javax.swing.JLabel();
        sldInicio = new javax.swing.JSlider();
        sldFim = new javax.swing.JSlider();
        sldPasso = new javax.swing.JSlider();
        bntCont = new javax.swing.JButton();
        jNum1 = new javax.swing.JLabel();
        jNUm2 = new javax.swing.JLabel();
        jNum3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaResul = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInicio.setText("Início");
        getContentPane().add(jInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 1, 37, -1));

        jFim.setText("Fim");
        getContentPane().add(jFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 27, 37, -1));

        jPasso.setText("Passo");
        getContentPane().add(jPasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 53, 37, -1));

        sldInicio.setMaximum(20);
        sldInicio.setValue(0);
        sldInicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldInicioStateChanged(evt);
            }
        });
        getContentPane().add(sldInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 0, -1, -1));

        sldFim.setMaximum(20);
        sldFim.setValue(0);
        sldFim.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldFimStateChanged(evt);
            }
        });
        getContentPane().add(sldFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 26, -1, -1));

        sldPasso.setMaximum(10);
        sldPasso.setValue(1);
        sldPasso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldPassoStateChanged(evt);
            }
        });
        getContentPane().add(sldPasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 52, -1, -1));

        bntCont.setText("Contar");
        bntCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntContActionPerformed(evt);
            }
        });
        getContentPane().add(bntCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 163, -1, -1));

        jNum1.setText("0");
        getContentPane().add(jNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 1, 16, -1));

        jNUm2.setText("0");
        getContentPane().add(jNUm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 27, 37, -1));

        jNum3.setText("1");
        getContentPane().add(jNum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 53, 37, -1));

        txtAreaResul.setColumns(20);
        txtAreaResul.setRows(5);
        jScrollPane2.setViewportView(txtAreaResul);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 6, -1, 294));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntContActionPerformed
        // TODO add your handling code here:
        
       int incio = sldInicio.getValue();
       int fim = sldFim.getValue();
       int passo = sldPasso.getValue();
       
       // Limpa o conteúdo anterior da área de texto
       txtAreaResul.setText("");
       
       // Faz a contagem de 'inicio' até 'fim', com o intervalo de 'passo'
       for(int i = incio; i <= fim; i += passo){
           // Adiciona cada número da contagem na área de texto, seguido de quebra de linha
           txtAreaResul.append(i + "\n");
       }
       
       
    }//GEN-LAST:event_bntContActionPerformed

    private void sldInicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldInicioStateChanged
        // TODO add your handling code here:
         // Pega o valor atual do slider de início
        int vlAtual = sldInicio.getValue();
        
        // Mostra o valor atual na label jNum1
        jNum1.setText(String.valueOf(vlAtual));
    }//GEN-LAST:event_sldInicioStateChanged

    private void sldFimStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldFimStateChanged
        // TODO add your handling code here:
         // Pega o valor atual do slider de fim
        int vlAtual = sldFim.getValue();
        
        // Mostra o valor atual na label jNUm2
        jNUm2.setText(String.valueOf(vlAtual));
    }//GEN-LAST:event_sldFimStateChanged

    private void sldPassoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldPassoStateChanged
        // TODO add your handling code here:
        // Pega o valor atual do slider de passo
        int valPasso = sldPasso.getValue();
        
        // Mostra o valor atual na label jNum3
       jNum3.setText(String.valueOf(valPasso));
    }//GEN-LAST:event_sldPassoStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Repetição().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCont;
    private javax.swing.JLabel jFim;
    private javax.swing.JLabel jInicio;
    private javax.swing.JLabel jNUm2;
    private javax.swing.JLabel jNum1;
    private javax.swing.JLabel jNum3;
    private javax.swing.JLabel jPasso;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider sldFim;
    private javax.swing.JSlider sldInicio;
    private javax.swing.JSlider sldPasso;
    private javax.swing.JTextArea txtAreaResul;
    // End of variables declaration//GEN-END:variables
}
